--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/oh-my-pmmp
build-by-default: true
branches:
  - main
projects:
  oh-my-pmmp:
    path: ""
    icon: assets/icon.png
    libs:
      - src: React/Promise/Promise
        version: ^0.0.1
      - src: thebigcrafter/Commando/Commando
        version: ^3.3.0
      - src: thebigcrafter/Hydrogen/Hydrogen
        version: ^1.0.0
...
