--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/oh-my-pmmp
build-by-default: true
branches:
  - main
projects:
  oh-my-pmmp:
    path: ""
    icon: assets/icon.png
    libs:
      - src: thebigcrafter/promise/promise
        version: ^2.9.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
    lint:
      phpstan: true
...
