--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MintoD/oh-my-pmmp
build-by-default: true
branches:
- main
projects:
  oh-my-pmmp:
    path: ""
    icon: assets/icon.png
    libs:
      - src: DavidGlitch04/promise/promise
        version: ^2.9.0
    lint:
      phpstan: false
...
