name: oh-my-pmmp
author: thebigcrafter
version: 2023.12
load: STARTUP
description: A plugin manager for PocketMine-MP
api: [5.0.0]
main: thebigcrafter\omp\OhMyPMMP

permissions:
  oh-my-pmmp.cmds:
    description: Allow players to use all commands of Oh My PMMP
    default: op
  oh-my-pmmp.help:
    description: Allow players to list available subcommands
    default: op
  oh-my-pmmp.version:
    description: Allow players to get plugin version
    default: op
  oh-my-pmmp.install:
    description: Allow players to install plugin
    default: op
  oh-my-pmmp.remove:
    description: Allow players to remove plugin
    default: op
  oh-my-pmmp.update:
    description: Allow players to update cached data
    default: op
  oh-my-pmmp.list:
    description: Allow players to list available plugins or installed plugins
    default: op
  oh-my-pmmp.show:
    description: Allow players to get details about a plugin
    default: op
  oh-my-pmmp.upgrade:
    description: Allow players to upgrade plugin
    default: op
  oh-my-pmmp.extract:
    description: Allow players to extract plugin Phar file into a folder
    default: op
  oh-my-pmmp.enable:
    description: Allow players to enable a disabled plugin
    default: op
  oh-my-pmmp.disable:
    description: Allow players to disable a plugin
    default: op