name: oh-my-pmmp
author: MintoD
version: 1.2.0
description: A plugin manager for OhMyPMMP
api: 4.0.0
main: thebigcrafter\OhMyPMMP\OhMyPMMP
src-namespace-prefix: thebigcrafter\OhMyPMMP

permissions:
  ohmypmmp.install.cmd:
    description: Allow players to install plugin
    default: op
  ohmypmmp.remove.cmd:
    description: Allow players to remove plugin
    default: op
  ohmypmmp.upgrade.cmd:
    description: Allow players to upgrade plugin
    default: op
