version: 2

jobs:
  build:
    docker:
      - image: circleci/php:8.0.14
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zipchunkutils2 crypto ctype curl date gmp hash igbinary json leveldb mbstring morton openssl pcre phar pthreads reflection simplexml sockets spl yaml zip zlib

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install

      - run: composer run-script analyse-src
