title: Oh My PMMP
description: Async plugin manager for PocketMine-MP
baseurl: "/"
url: "https://thebigcrafter.github.io/oh-my-pmmp" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
logo: "/assets/logo.png"

aux_links:
  "Oh My PMMP on GitHub":
    - "//github.com/thebigcrafter/oh-my-pmmp"
aux_links_new_tab: true

color_scheme: dark

footer_content: "Copyright &copy; 2022 thebigcrafter. Distributed by an <a href=\"https://github.com/thebigcrafter/oh-my-pmmp/blob/main/LICENSE\">GPL-3.0 license.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"


gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/thebigcrafter/oh-my-pmmp/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

permalink: pretty
heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"