name: Build plugin

on:
  push:

jobs:
  build-phar:
    name: Build PHAR file
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 🐘
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: 8.1
          install-path: "./bin"
          pm-version-major: "5"

      - name: Download pharynx
        run: wget https://github.com/SOF3/pharynx/releases/download/0.3.6/pharynx.phar
  
      - name: Run pharynx
        run: php -d phar.readonly=0 pharynx.phar -i ./ -o ./oh-my-pmmp.phar

      - uses: actions/upload-artifact@v3
        with:
          name: oh-my-pmmp
          path: oh-my-pmmp.phar
