name: Build plugin

on:
  push:

jobs:
  build-phar:
    name: Build PHAR file
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 🐘
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: 8.1
          install-path: "./bin"
          pm-version-major: "5"

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - uses: "ramsey/composer-install@v2"
        with:
          working-directory: "vendor-bin/box"
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - name: Run Box
        run: ./vendor-bin/box/vendor/bin/box compile

      - uses: actions/upload-artifact@v3
        with:
          name: oh-my-pmmp
          path: oh-my-pmmp.phar
