name: CI

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: composer run-script analyse

  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.27.1
        with:
          php-version: 8.1
          tools: php-cs-fixer:3.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi