name: PHPStan

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --dev
      
    - name: Run PHPStan analysis
      run: composer run-script analyse
